version: '3'

services:
  pdf_pseudo_api:
    container_name: pdf_pseudo_api
    restart: always
    build: https://github.com/luclemot/pseudo_pdf_tool.git#main:api
    ports:
      - "8012:8000"
    command: python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
    

  nginx:
    container_name: pdf_nginx
    restart: always
    build: ./nginx
    ports:
      - "81:80"
    depends_on:
      - pdf_pseudo_api