version: '3'

services:
  pdf_pseudo_api:
    container_name: pdf_pseudo_api
    restart: always
    build: https://github.com/luclemot/pseudo_pdf_tool.git#main:pdf_pseudo_api
    ports:
      - "8011:8000"
    command: gunicorn -w 2 --timeout 90 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - pdf_pseudo_api