name: pseudo_pdf_env
dependencies:
  - gunicorn=20.0.4=py37_0
  - pip:
    - aiofiles==22.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - aiosqlite==0.19.0
    - anonymeter==0.0.1
    - anonymizer==0.0.6
    - anonympy==0.3.7
    - ansi2html==1.8.0
    - aiofiles==22.1.0
    - nsi2html==1.8.0
    - nyio==3.6.2
    - ppdirs==1.4.4
    - pturl==0.5.2
    - rgcomplete==1.10.3
    - rgon2-cffi==21.3.0
    - rgon2-cffi-bindings==21.2.0
    - rrow==1.2.3
    - sgiref==3.6.0
    - sttokens==2.2.1
    - sync-timeout==4.0.2
    - ttr==0.3.1
    - ttrs==23.1.0
    - zure-core==1.26.4
    - zure-storage-blob==12.16.0
    - abel==2.12.1
    - ackcall==0.2.0
    - crypt==3.2.0
    - eautifulsoup4==4.8.2
    - lack==21.10b0
    - leach==5.0.1
    - linker==1.4
    - lis==0.7.9
    - oto==2.49.0
    - oto3==1.16.63
    - otocore==1.19.63
    - oxing==0.1.4
    - pemb==0.3.4
    - rlapi==0.8.3
    - uild==0.10.0
    - acheControl==0.12.11
    - achetools==5.3.0
    - achy==0.3.0
    - ape-dataframes==0.3.1
    - atalogue==2.0.8
    - atkin==0.8.10
    - atkin-pkg==0.4.24
    - ertifi==2020.6.20
    - ffi==1.15.1
    - hardet==3.0.4
    - harset-normalizer==2.0.12
    - i-info==0.3.0
    - leo==1.0.0a5
    - lick==8.0.3
    - loudpickle==2.0.0
    - make==3.26.3
    - olorama==0.4.4
    - omm==0.1.3
    - ommand-not-found==0.3
    - ompressed-rtf==1.0.6
    - onfection==0.0.4
    - onfigobj==5.0.8
    - onfigparser==5.3.0
    - onllu==4.5.3
    - ontourpy==1.0.7
    - oreapi==2.3.3
    - oreschema==0.0.4
    - rashtest==0.3.1
    - ryptography==3.4.8
    - upshelpers==1.0
    - ustomtkinter==5.1.3
    - ycler==0.11.0
    - ymem==2.0.7
    - arkdetect==0.8.0
    - ash==2.11.0
    - ash-bootstrap-components==1.4.1
    - ash-core-components==2.0.0
    - ash-html-components==2.0.0
    - ash-table==5.0.0
    - atasets==2.13.1
    - bus-python==1.2.18
    - ebugpy==1.6.7
    - ecorator==5.1.1
    - efer==1.0.6
    - efusedxml==0.7.1
    - eprecated==1.2.14
    - eprecation==2.1.0
    - ill==0.3.6
    - istlib==0.3.6
    - istro==1.7.0
    - istro-info===1.1build1
    - jango==3.2.16
    - jango-annoying==0.10.6
    - jango-cors-headers==3.6.0
    - jango-debug-toolbar==3.2.1
    - jango-extensions==3.1.0
    - jango-filter==2.4.0
    - jango-model-utils==4.1.1
    - jango-ranged-fileresponse==0.1.2
    - jango-rest-swagger==2.2.0
    - jango-rq==2.5.1
    - jango-storages==1.12.3
    - jango-user-agents==0.4.0
    - jangorestframework==3.13.1
    - ocutils==0.17.1
    - ocx2txt==0.8
    - ocxedit==1.0.1
    - rf-dynamic-fields==0.3.0
    - rf-flex-fields==0.9.5
    - rf-generators==0.3.0
    - rf-yasg==1.20.0
    - ulwich==0.20.50
    - uplicity==0.8.21
    - ynamic-reconfigure==1.7.2
    - asyocr==1.7.0
    - bcdic==1.1.1
    - dsnlp==0.7.4
    - dspdf==0.5.3
    - mpy==3.3.4
    - telemetry==0.3.0
    - xceptiongroup==1.1.1
    - xecuting==1.2.0
    - xpiringdict==1.2.2
    - xtract-msg==0.28.7
    - aker==18.5.1
    - astapi==0.100.0
    - asteners==0.14.1
    - astjsonschema==2.16.3
    - ilelock==3.12.0
    - lair==0.12.2
    - lask==2.2.5
    - onttools==4.39.3
    - qdn==1.5.1
    - rontend==0.0.3
    - rozenlist==1.3.3
    - sspec==2023.4.0
    - tfy==6.1.1
    - uture==0.18.2
    - csfs==2023.4.0
    - down==4.4.0
    - encpp==0.6.5
    - enlisp==0.4.18
    - enmsg==0.5.16
    - enpy==0.6.16
    - ensim==4.3.1
    - oogle-api-core==2.10.0
    - oogle-auth==2.21.0
    - oogle-auth-oauthlib==1.0.0
    - oogle-cloud-appengine-logging==1.1.0
    - oogle-cloud-audit-log==0.2.0
    - oogle-cloud-core==2.3.2
    - oogle-cloud-logging==2.7.2
    - oogle-cloud-storage==2.5.0
    - oogle-crc32c==1.5.0
    - oogle-resumable-media==2.3.3
    - oogleapis-common-protos==1.56.4
    - rpc-google-iam-v1==0.12.3
    - rpcio==1.54.2
    - rpcio-status==1.48.2
    - 11==0.14.0
    - tml5lib==1.1
    - tmlmin==0.1.12
    - ttplib2==0.20.2
    - uggingface-hub==0.14.1
    - yperopt==0.2.7
    - dna==3.3
    - mageio==2.30.0
    - MAPClient==2.1.0
    - mg2pdf==0.4.4
    - mportlib-metadata==6.6.0
    - nflection==0.5.1
    - niconfig==2.0.0
    - nstaller==0.6.0
    - pykernel==6.22.0
    - python==8.12.0
    - python-genutils==0.2.0
    - sodate==0.6.1
    - soduration==20.11.0
    - tsdangerous==2.1.2
    - types==1.2.0
    - anome==0.4.2
    - araco.classes==3.2.3
    - edi==0.18.2
    - eepney==0.7.1
    - inja2==3.1.2
    - mespath==0.10.0
    - oblib==1.2.0
    - son5==0.9.14
    - sonpointer==2.3
    - sonschema==4.17.3
    - upyter-events==0.6.3
    - upyter-ydoc==0.2.4
    - upyter_client==8.2.0
    - upyter_core==5.3.0
    - upyter_server==2.5.0
    - upyter_server_fileid==0.9.0
    - upyter_server_terminals==0.4.4
    - upyter_server_ydoc==0.8.0
    - upyterlab==3.6.3
    - upyterlab-pygments==0.2.2
    - upyterlab_server==2.22.1
    - eyring==23.13.1
    - iwisolver==1.4.4
    - modes==0.12.2
    - abel-studio==1.7.3
    - abel-studio-converter==0.0.51
    - abel-studio-tools==0.0.2
    - angcodes==3.3.0
    - angdetect==1.0.9
    - anguage-selector==0.1
    - aunchdarkly-server-sdk==7.5.0
    - aunchpadlib==1.10.16
    - azr.restfulclient==0.14.4
    - azr.uri==1.0.6
    - azy_loader==0.2
    - evenshtein==0.21.1
    - it==16.0.2
    - lvmlite==0.40.0
    - ockfile==0.12.2
    - oguru==0.6.0
    - ooseversion==1.2.0
    - ouis==3.20.0
    - xml==4.9.2
    - acaroonbakery==1.3.1
    - ako==1.1.3
    - arkdown-it-py==2.2.0
    - arkupSafe==2.1.3
    - atplotlib==3.7.1
    - atplotlib-inline==0.1.6
    - durl==0.1.2
    - istune==2.0.5
    - onotonic==1.6
    - ore-click==0.1.2
    - ore-itertools==8.10.0
    - pld3==0.3
    - pmath==1.3.0
    - sgpack==1.0.5
    - ultidict==6.0.4
    - ultiprocess==0.70.14
    - urmurhash==1.0.9
    - ypy-extensions==0.4.3
    - bclassic==1.0.0
    - bclient==0.7.4
    - bconvert==7.4.0
    - bformat==5.8.0
    - est-asyncio==1.5.6
    - etifaces==0.11.0
    - etworkx==2.8.8
    - ibabel==5.1.0
    - inja==1.11.1
    - ipype==1.8.6
    - ltk==3.6.7
    - otebook==6.5.4
    - otebook_shim==0.2.3
    - umba==0.57.0
    - umpy==1.25.0
    - vidia-cublas-cu11==11.10.3.66
    - vidia-cuda-cupti-cu11==11.7.101
    - vidia-cuda-nvrtc-cu11==11.7.99
    - vidia-cuda-runtime-cu11==11.7.99
    - vidia-cudnn-cu11==8.5.0.96
    - vidia-cufft-cu11==10.9.0.58
    - vidia-curand-cu11==10.2.10.91
    - vidia-cusolver-cu11==11.4.0.1
    - vidia-cusparse-cu11==11.7.4.91
    - vidia-nccl-cu11==2.14.3
    - vidia-nvtx-cu11==11.7.91
    - authlib==3.2.0
    - lefile==0.46
    - penapi-codec==1.3.2
    - pencv-python==4.7.0.72
    - pencv-python-headless==4.7.0.72
    - rdered-set==4.0.2
    - ackaging==23.1
    - andas==1.3.5
    - andocfilters==1.5.0
    - aramiko==2.9.3
    - arso==0.8.3
    - athlib==1.0.1
    - athspec==0.9.0
    - athy==0.10.1
    - atsy==0.5.3
    - DF-Layout-Scanner==1.3.3
    - df2image==1.16.3
    - df2jpg==1.1
    - dfminer.six==20191110
    - endulum==2.1.2
    - ep517==0.8.2
    - expect==4.8.0
    - ickleshare==0.7.5
    - ikepdf==7.2.0
    - illow==9.3.0
    - kginfo==1.9.6
    - latformdirs==2.5.2
    - lotly==5.14.1
    - luggy==1.0.0
    - oetry==1.2.0
    - oetry-core==1.1.0
    - oetry-plugin-export==1.1.2
    - oppler-utils==0.1.0
    - ptree==3.1
    - reshed==3.0.8
    - rometheus-client==0.16.0
    - rompt-toolkit==3.0.38
    - roto-plus==1.22.2
    - rotobuf==3.20.3
    - rov==2.0.0
    - sutil==5.9.5
    - sycopg2-binary==2.9.6
    - typrocess==0.7.0
    - ure-eval==0.2.2
    - y4j==0.10.9.7
    - yarrow==11.0.0
    - yasn1==0.5.0
    - yasn1-modules==0.3.0
    - ycairo==1.20.1
    - ycanon==1.0.0.post5
    - yclipper==1.3.0.post4
    - ycparser==2.21
    - ycryptodome==3.17
    - ycups==2.0.1
    - ydantic==1.10.7
    - ydot==1.4.2
    - ygments==2.15.1
    - yGObject==3.42.1
    - yJWT==2.3.0
    - ylev==1.4.0
    - ymacaroons==0.13.0
    - yMuPDF==1.22.3
    - yNaCl==1.5.0
    - ypandoc==1.7.0
    - yparsing==2.4.7
    - ypdf==3.9.0
    - yPDF2==3.0.1
    - ypdfium2==2.11.0
    - yproject_hooks==1.0.0
    - yRFC3339==1.1
    - yrsistent==0.19.3
    - ysimstring==1.2.1
    - ySocks==1.7.1
    - yspark==3.4.0
    - ystow==0.5.0
    - ytesseract==0.3.10
    - ytest==7.3.1
    - ython-apt==2.4.0+ubuntu1
    - ython-bidi==0.4.2
    - ython-dateutil==2.8.2
    - ython-debian===0.1.43ubuntu1
    - ython-docx==0.8.11
    - ython-IO==0.3
    - ython-json-logger==2.0.4
    - ython-multipart==0.0.6
    - ython-pptx==0.6.21
    - ytorch_revgrad==0.2.0
    - ytz==2023.3
    - ytz-deprecation-shim==0.1.0.post0
    - ytzdata==2020.1
    - yWavelets==1.4.1
    - yxdg==0.27
    - yxnat==1.5
    - yYAML==5.4.1
    - yzmq==25.0.2
    - apidfuzz==2.15.1
    - dflib==6.3.2
    - edis==4.5.5
    - egex==2022.3.2
    - eportlab==3.6.13
    - equests==2.28.0
    - equests-oauthlib==1.3.1
    - equests-toolbelt==0.9.1
    - etrying==1.3.4
    - fc3339==6.2
    - fc3339-validator==0.1.4
    - fc3986-validator==0.1.1
    - ich==13.3.4
    - oman==3.3
    - oslib==1.15.8
    - ospkg==1.3.0
    - py2==3.5.1
    - q==1.10.1
    - sa==4.9
    - uamel.yaml==0.17.26
    - uamel.yaml.clib==0.2.7
    - ules==2.2
    - 3transfer==0.3.7
    - arus==0.7.4
    - arus-data-spec-public==3.5.8
    - cikit-image==0.20.0
    - cikit-learn==1.2.2
    - cipy==1.10.1
    - creen-resolution-extra==0.0.0
    - eaborn==0.12.2
    - ecretStorage==3.3.1
    - egtok==1.5.11
    - emver==2.13.0
    - end2Trash==1.8.2
    - entencepiece==0.1.98
    - entry-sdk==1.22.2
    - hapely==2.0.1
    - hellingham==1.5.0.post1
    - implejson==3.19.1
    - ix==1.12.0
    - klearn==0.0.post4
    - mart-open==6.3.0
    - niffio==1.3.0
    - ortedcontainers==2.4.0
    - oupsieve==2.4.1
    - pacy==3.5.2
    - pacy-alignments==0.9.0
    - pacy-legacy==3.0.12
    - pacy-loggers==1.0.4
    - pacy-transformers==1.2.3
    - peechRecognition==3.8.1
    - qlitedict==2.1.0
    - qlparse==0.4.4
    - rsly==2.4.6
    - tack-data==0.6.2
    - tarlette==0.27.0
    - tats==0.1.2a0
    - tatsmodels==0.13.5
    - topwatch.py==2.0.1
    - ympy==1.11.1
    - ystemd-python==234
    - abulate==0.9.0
    - enacity==8.2.2
    - erminado==0.17.1
    - extract==1.6.5
    - exttable==1.6.7
    - hinc==8.1.9
    - hreadpoolctl==3.1.0
    - ifffile==2023.4.12
    - inycss2==1.2.1
    - okenizers==0.13.3
    - oml==0.10.1
    - omli==2.0.1
    - omlkit==0.11.8
    - orch==2.0.1
    - orchvision==0.15.2
    - ornado==6.3.1
    - qdm==4.65.0
    - raitlets==5.9.0
    - raits==6.3.2
    - ransformer-smaller-training-vocab==0.2.4
    - ransformers==4.28.1
    - riton==2.0.0
    - rove-classifiers==2023.5.2
    - yper==0.7.0
    - yping_extensions==4.5.0
    - zdata==2023.3
    - zlocal==4.3
    - a-parser==0.16.1
    - buntu-advantage-tools==8001
    - buntu-drivers-common==0.0.0
    - fw==0.36.1
    - json==5.7.0
    - mls-downloader==0.1.1
    - nattended-upgrades==0.1
    - ri-template==1.2.0
    - ritemplate==4.1.1
    - rllib3==1.26.15
    - sb-creator==0.3.7
    - ser-agents==2.2.0
    - vicorn==0.22.0
    - alidators==0.20.0
    - irtualenv==20.23.0
    - adllib==1.3.6
    - and==0.6.11
    - asabi==1.1.1
    - cwidth==0.2.6
    - ebcolors==1.13
    - ebencodings==0.5.1
    - ebsocket-client==1.5.2
    - erkzeug==2.2.3
    - ikipedia-API==0.5.8
    - ordcloud==1.9.1.1
    - rapt==1.15.0
    - dg==5
    - kit==0.0.0
    - lrd==1.2.0
    - lsxWriter==3.1.2
    - mljson==0.2.0
    - xhash==3.2.0
    - py==0.5.9
    - arl==1.9.2
    - py-websocket==0.8.2
    - ipp==1.0.0
