name: pdf_pseudo_env
dependencies:
  - python=3.10
  - conda=23.5.2
  - pip:
    - uvicorn == 0.22.0
    - aiofiles==23.1.0
    - annotated-types==0.5.0
    - anyio==3.7.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - ci-info==0.3.0
    - click==8.1.6
    - cmake==3.27.0
    - configobj==5.0.8
    - configparser==6.0.0
    - easyocr==1.7.0
    - etelemetry==0.3.0
    - exceptiongroup==1.1.2
    - fastapi==0.100.0
    - filelock==3.12.2
    - fitz==0.0.1.dev2
    - fsspec==2023.6.0
    - future==0.18.3
    - httplib2==0.22.0
    - huggingface-hub==0.16.4
    - idna==3.4
    - imageio==2.31.1
    - isodate==0.6.1
    - Jinja2==3.1.2
    - lazy_loader==0.3
    - lit==16.0.6
    - looseversion==1.3.0
    - lxml==4.9.3
    - MarkupSafe==2.1.3
    - mpmath==1.3.0
    - networkx==3.1
    - nibabel==5.1.0
    - ninja==1.11.1
    - nipype==1.8.6
    - numpy==1.25.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - opencv-python-headless==4.8.0.74
    - packaging==23.1
    - pandas==2.0.3
    - pathlib==1.0.1
    - Pillow==10.0.0
    - protobuf==4.23.4
    - prov==2.0.0
    - pyclipper==1.3.0.post4
    - pydantic==2.0.3
    - pydantic_core==2.3.0
    - pydot==1.4.2
    - PyMuPDF==1.22.3
    - pyparsing==3.1.0
    - python-bidi==0.4.2
    - python-dateutil==2.8.2
    - pytz==2023.3
    - PyWavelets==1.4.1
    - pyxnat==1.6
    - PyYAML==6.0.1
    - random2==1.0.1
    - rdflib==6.3.2
    - regex==2023.6.3
    - requests==2.31.0
    - safetensors==0.3.1
    - scikit-image==0.21.0
    - scipy==1.11.1
    - sentencepiece==0.1.99
    - shapely==2.0.1
    - simplejson==3.19.1
    - six==1.16.0
    - sniffio==1.3.0
    - starlette==0.27.0
    - sympy==1.12
    - tifffile==2023.7.18
    - tokenizers==0.13.3
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - traits==6.3.2
    - transformers==4.31.0
    - triton==2.0.0
    - typing==3.7.4.3
    - typing_extensions==4.7.1
    - tzdata==2023.3
    - urllib3==2.0.4
    - Wand==0.6.11

