name: pseudo_pdf_env
dependencies:
  - gunicorn=20.1.0
  - python=3.10
  - conda=23.5.2
  - pip:
    - aiofiles==22.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - aiosqlite==0.19.0
    - anonymeter==0.0.1
    - anonymizer==0.0.6
    - ansi2html==1.8.0
    - anyio==3.6.2
    - appdirs==1.4.4
    - argcomplete==1.10.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asgiref==3.6.0
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attr==0.3.1
    - attrs==23.1.0
    - azure-core==1.26.4
    - azure-storage-blob==12.16.0
    - Babel==2.12.1
    - backcall==0.2.0
    - bcrypt==3.2.0
    - beautifulsoup4==4.8.2
    - black==21.10b0
    - bleach==5.0.1
    - blinker==1.4
    - blis==0.7.9
    - boto==2.49.0
    - boto3==1.16.63
    - botocore==1.19.63
    - boxing==0.1.4
    - bpemb==0.3.4
    - build==0.10.0
    - CacheControl==0.12.11
    - cachetools==5.3.0
    - cachy==0.3.0
    - cape-dataframes==0.3.1
    - catalogue==2.0.8
    - certifi==2020.6.20
    - cffi==1.15.1
    - chardet==3.0.4
    - charset-normalizer==2.0.12
    - ci-info==0.3.0
    - cleo==1.0.0a5
    - click==8.0.3
    - cloudpickle==2.0.0
    - cmake==3.26.3
    - colorama==0.4.4
    - comm==0.1.3
    - compressed-rtf==1.0.6
    - confection==0.0.4
    - configobj==5.0.8
    - configparser==5.3.0
    - conllu==4.5.3
    - contourpy==1.0.7
    - coreapi==2.3.3
    - coreschema==0.0.4
    - crashtest==0.3.1
    - cryptography==3.4.8
    - customtkinter==5.1.3
    - cycler==0.11.0
    - cymem==2.0.7
    - darkdetect==0.8.0
    - dash==2.11.0
    - dash-bootstrap-components==1.4.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - datasets==2.13.1
    - dbus-python==1.2.18
    - debugpy==1.6.7
    - decorator==5.1.1
    - defer==1.0.4
    - defusedxml==0.7.1
    - Deprecated==1.2.14
    - deprecation==2.1.0
    - dill==0.3.6
    - distlib==0.3.6
    - distro==1.7.0
    - Django==3.2.16
    - django-annoying==0.10.6
    - django-cors-headers==3.6.0
    - django-debug-toolbar==3.2.1
    - django-extensions==3.1.0
    - django-filter==2.4.0
    - django-model-utils==4.1.1
    - django-ranged-fileresponse==0.1.2
    - django-rest-swagger==2.2.0
    - django-rq==2.5.1
    - django-storages==1.12.3
    - django-user-agents==0.4.0
    - djangorestframework==3.13.1
    - docutils==0.17.1
    - docx2txt==0.8
    - docxedit==1.0.1
    - drf-dynamic-fields==0.3.0
    - drf-flex-fields==0.9.5
    - drf-generators==0.3.0
    - drf-yasg==1.20.0
    - dulwich==0.20.50
    - easyocr==1.7.0
    - ebcdic==1.1.1
    - edsnlp==0.7.4
    - edspdf==0.5.3
    - empy==3.3.4
    - etelemetry==0.3.0
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - expiringdict==1.2.2
    - extract-msg==0.28.7
    - Faker==18.5.1
    - fastapi==0.100.0
    - fasteners==0.14.1
    - fastjsonschema==2.16.3
    - filelock==3.12.0
    - flair==0.12.2
    - Flask==2.2.5
    - fonttools==4.39.3
    - fqdn==1.5.1
    - frontend==0.0.3
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - ftfy==6.1.1
    - future==0.18.2
    - gcsfs==2023.4.0
    - gdown==4.4.0
    - genlisp==0.4.18
    - genmsg==0.5.16
    - genpy==0.6.16
    - gensim==4.3.1
    - google-api-core==2.10.0
    - google-auth==2.21.0
    - google-auth-oauthlib==1.0.0
    - google-cloud-appengine-logging==1.1.0
    - google-cloud-audit-log==0.2.0
    - google-cloud-core==2.3.2
    - google-cloud-logging==2.7.2
    - google-cloud-storage==2.5.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.3.3
    - googleapis-common-protos==1.56.4
    - grpc-google-iam-v1==0.12.3
    - grpcio==1.54.2
    - grpcio-status==1.48.2
    - h11==0.14.0
    - html5lib==1.1
    - htmlmin==0.1.12
    - httplib2==0.20.2
    - huggingface-hub==0.14.1
    - hyperopt==0.2.7
    - idna==3.3
    - imageio==2.30.0
    - IMAPClient==2.1.0
    - img2pdf==0.4.4
    - importlib-metadata==6.6.0
    - inflection==0.5.1
    - iniconfig==2.0.0
    - installer==0.6.0
    - ipykernel==6.22.0
    - ipython==8.12.0
    - ipython-genutils==0.2.0
    - isodate==0.6.1
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - itypes==1.2.0
    - Janome==0.4.2
    - jaraco.classes==3.2.3
    - jedi==0.18.2
    - jeepney==0.7.1
    - Jinja2==3.1.2
    - jmespath==0.10.0
    - joblib==1.2.0
    - json5==0.9.14
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-events==0.6.3
    - jupyter-ydoc==0.2.4
    - jupyter_client==8.2.0
    - jupyter_core==5.3.0
    - jupyter_server==2.5.0
    - jupyter_server_fileid==0.9.0
    - jupyter_server_terminals==0.4.4
    - jupyter_server_ydoc==0.8.0
    - jupyterlab==3.6.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab_server==2.22.1
    - keyring==23.13.1
    - kiwisolver==1.4.4
    - kmodes==0.12.2
    - label-studio==1.7.3
    - label-studio-converter==0.0.51
    - label-studio-tools==0.0.2
    - langcodes==3.3.0
    - langdetect==1.0.9
    - language-selector==0.1
    - launchdarkly-server-sdk==7.5.0
    - launchpadlib==1.10.16
    - lazr.restfulclient==0.14.4
    - lazr.uri==1.0.6
    - lazy_loader==0.2
    - Levenshtein==0.21.1
    - lit==16.0.2
    - llvmlite==0.40.0
    - lockfile==0.12.2
    - loguru==0.6.0
    - looseversion==1.2.0
    - louis==3.20.0
    - lxml==4.9.2
    - macaroonbakery==1.3.1
    - Mako==1.1.3
    - markdown-it-py==2.2.0
    - MarkupSafe==2.1.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==2.0.5
    - monotonic==1.6
    - more-click==0.1.2
    - more-itertools==8.10.0
    - mpld3==0.3
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - multiprocess==0.70.14
    - murmurhash==1.0.9
    - mypy-extensions==0.4.3
    - nbclassic==1.0.0
    - nbclient==0.7.4
    - nbconvert==7.4.0
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - netifaces==0.11.0
    - networkx==2.8.8
    - nibabel==5.1.0
    - ninja==1.11.1
    - nipype==1.8.6
    - nltk==3.6.7
    - notebook==6.5.4
    - notebook_shim==0.2.3
    - numba==0.57.0
    - numpy==1.25.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.0
    - olefile==0.46
    - openapi-codec==1.3.2
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - ordered-set==4.0.2
    - packaging==23.1
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - paramiko==2.9.3
    - parso==0.8.3
    - pathlib==1.0.1
    - pathspec==0.9.0
    - pathy==0.10.1
    - patsy==0.5.3
    - PDF-Layout-Scanner==1.3.3
    - pdf2image==1.16.3
    - pdf2jpg==1.1
    - pdfminer.six==20191110
    - pendulum==2.1.2
    - pep517==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pikepdf==7.2.0
    - Pillow==9.3.0
    - pkginfo==1.9.6
    - platformdirs==2.5.2
    - plotly==5.14.1
    - pluggy==1.0.0
    - poetry==1.2.0
    - poetry-core==1.1.0
    - poetry-plugin-export==1.1.2
    - poppler-utils==0.1.0
    - pptree==3.1
    - preshed==3.0.8
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - proto-plus==1.22.2
    - protobuf==3.20.3
    - prov==2.0.0
    - psutil==5.9.5
    - psycopg2-binary==2.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py4j==0.10.9.7
    - pyarrow==11.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycairo==1.20.1
    - pycanon==1.0.0.post5
    - pyclipper==1.3.0.post4
    - pycparser==2.21
    - pycryptodome==3.17
    - pycups==2.0.1
    - pydantic==1.10.7
    - pydot==1.4.2
    - Pygments==2.15.1
    - PyGObject==3.42.1
    - PyJWT==2.3.0
    - pylev==1.4.0
    - pymacaroons==0.13.0
    - PyMuPDF==1.22.3
    - PyNaCl==1.5.0
    - pypandoc==1.7.0
    - pyparsing==2.4.7
    - pypdf==3.9.0
    - PyPDF2==3.0.1
    - pypdfium2==2.11.0
    - pyproject_hooks==1.0.0
    - pyRFC3339==1.1
    - pyrsistent==0.19.3
    - pysimstring==1.2.1
    - PySocks==1.7.1
    - pyspark==3.4.0
    - pystow==0.5.0
    - pytesseract==0.3.10
    - pytest==7.3.1
    - python-apt==2.4.0+ubuntu1
    - python-bidi==0.4.2
    - python-dateutil==2.8.2
    - python-debian===0.1.43ubuntu1
    - python-docx==0.8.11
    - Python-IO==0.3
    - python-json-logger==2.0.4
    - python-multipart==0.0.6
    - python-pptx==0.6.21
    - pytorch_revgrad==0.2.0
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pytzdata==2020.1
    - PyWavelets==1.4.1
    - pyxdg==0.27
    - pyxnat==1.5
    - PyYAML==5.4.1
    - pyzmq==25.0.2
    - rapidfuzz==2.15.1
    - rdflib==6.3.2
    - redis==4.5.5
    - regex==2022.3.2
    - reportlab==3.6.13
    - requests==2.28.0
    - requests-oauthlib==1.3.1
    - requests-toolbelt==0.9.1
    - retrying==1.3.4
    - rfc3339==6.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.3.4
    - roman==3.3
    - roslib==1.15.8
    - rospkg==1.3.0
    - rpy2==3.5.1
    - rq==1.10.1
    - rsa==4.9
    - ruamel.yaml==0.17.26
    - ruamel.yaml.clib==0.2.7
    - rules==2.2
    - s3transfer==0.3.7
    - sarus==0.7.4
    - sarus-data-spec-public==3.5.8
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - screen-resolution-extra==0.0.0
    - seaborn==0.12.2
    - SecretStorage==3.3.1
    - segtok==1.5.11
    - semver==2.13.0
    - Send2Trash==1.8.2
    - sentencepiece==0.1.98
    - sentry-sdk==1.22.2
    - shapely==2.0.1
    - shellingham==1.5.0.post1
    - simplejson==3.19.1
    - six==1.12.0
    - sklearn==0.0.post4
    - smart-open==6.3.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4.1
    - spacy==3.5.2
    - spacy-alignments==0.9.0
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - spacy-transformers==1.2.3
    - SpeechRecognition==3.8.1
    - sqlitedict==2.1.0
    - sqlparse==0.4.4
    - srsly==2.4.6
    - stack-data==0.6.2
    - starlette==0.27.0
    - stats==0.1.2a0
    - statsmodels==0.13.5
    - stopwatch.py==2.0.1
    - sympy==1.11.1
    - systemd-python==234
    - tabulate==0.9.0
    - tenacity==8.2.2
    - terminado==0.17.1
    - textract==1.6.5
    - texttable==1.6.7
    - thinc==8.1.9
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - toml==0.10.1
    - tomli==2.0.1
    - tomlkit==0.11.8
    - torch==2.0.1
    - torchvision==0.15.2
    - tornado==6.3.1
    - tqdm==4.65.0
    - traitlets==5.9.0
    - traits==6.3.2
    - transformer-smaller-training-vocab==0.2.4
    - transformers==4.28.1
    - triton==2.0.0
    - trove-classifiers==2023.5.2
    - typer==0.7.0
    - typing_extensions==4.5.0
    - tzdata==2023.3
    - tzlocal==4.3
    - ua-parser==0.16.1
    - ubuntu-advantage-tools==8001
    - ubuntu-drivers-common==0.0.0
    - ufw==0.36.1
    - ujson==5.7.0
    - umls-downloader==0.1.1
    - unattended-upgrades==0.1
    - uri-template==1.2.0
    - uritemplate==4.1.1
    - urllib3==1.26.15
    - usb-creator==0.3.7
    - user-agents==2.2.0
    - uvicorn==0.22.0
    - validators==0.20.0
    - virtualenv==20.23.0
    - wadllib==1.3.6
    - Wand==0.6.11
    - wasabi==1.1.1
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.2
    - Werkzeug==2.2.3
    - Wikipedia-API==0.5.8
    - wordcloud==1.9.1.1
    - wrapt==1.15.0
    - xdg==5
    - xkit==0.0.0
    - xlrd==1.2.0
    - XlsxWriter==3.1.2
    - xmljson==0.2.0
    - xxhash==3.2.0
    - y-py==0.5.9
    - yarl==1.9.2
    - ypy-websocket==0.8.2
    - zipp==1.0.0
